CC = gcc -ggdb

copy: copy.o
	$(CC) -o copy copy.o

copy.o: copy.c
	$(CC) -c copy.c

remove_directory: remove_directory.o
	$(CC) -o remove_directory remove_directory.o

remove_directory.o: remove_directory.c
	$(CC) -c remove_directory.c
